### ISSUE TITLE
fails to compile

### ISSUE THREAD

**Issue by blurymind** [defold/extension-videoplayer#3]
After trying to build, I get this:

![failedbuild](https://user-images.githubusercontent.com/6495061/37257247-7fced5e6-255e-11e8-8385-958115122ae2.PNG)
I'm on windows 10 btw

**Comment by britzl** [comment]
Fixed in commit: https://github.com/defold/extension-videoplayer/commit/99e1e2a5b928663c2e608a484f1598609e3234c6

**Comment by blurymind** [comment]
Thank you @britzl I am going to try it out in the weekend
